using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SystemView.ContentDisplays
{
    // To call DatalogDownloadAllAvailable = new DatalogDownloadAllAvailable();
    //
    // CLASS: DatalogDownloadAllAvailable
    //
    // Description: This class implements UI and back-end logic for the Datalog Download All Available download type selection of the PTE. This class initializes a WPF 
    //              component that builds the front end display of the download selection. The class is instanciated from a DisplayView instance that places
    //              this WPF display inside the Session Docking mechanism. This function places a static label on the UI, informing the user that the All Available
    //              datalog download option has been selected.
    //
    // Private Data:
    //
    // Public Get/Set Accessors:
    //
    // Public Methods:
    //
    // Private Methods:
    //
    // Constructors:
    //
    // Other DataTypes:
    //
    public partial class DatalogDownloadAllAvailable : UserControl
    {
        /// <summary>
        /// Default constructor for the DatalogDownloadAllAvailable Class. Creates the UI.
        /// </summary>
        public DatalogDownloadAllAvailable()
        {
            try
            {
                // Generate the UI. This calls the logic generated by the WPF compiler to build the display.
                InitializeComponent();
            }
            catch (Exception ex)
            {
                StringBuilder sb = new StringBuilder();
                sb.Append(String.Format("DatalogDownloadAllAvailable::Constructor-threw exception {0}", ex.ToString()));

                Console.WriteLine(sb.ToString());
            }
        }
    }
}
